# .github/workflows/ci.yml

name: Continuous Integration

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Compile contracts
      run: npx hardhat compile

    - name: Lint Solidity
      run: npx solhint 'contracts/**/*.sol'

    - name: Lint JavaScript/TypeScript
      run: npx eslint . --ext .js,.ts || true

    - name: Run tests
      run: npx hardhat test

    - name: Generate coverage report
      run: npx hardhat coverage --temp build --network hardhat

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.json
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    # Optional: Contract size report (can be commented out if not used)
    - name: Check contract sizes
      run: npx hardhat size-contracts

    # Optional: Deployment on tag/release
    # - name: Deploy to testnet/mainnet (manual approval recommended)
    #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    #   run: |
    #     npx hardhat run scripts/deploy.js --network mainnet
