name: OCOS DAO Full Matrix CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8, 3.10, 3.11]
        node-version: [16, 18]
        btc-network: [regtest, testnet]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install Node.js dependencies
        run: npm ci

      - name: Lint and security scan
        run: |
          pylint scripts/
          npm run lint
          npm audit

      - name: Run unit tests (Python)
        run: pytest

      - name: Run unit tests (Node.js)
        run: npm test

      - name: Run integration & scalability tests
        run: python scripts/scalability_test.py

      - name: Run explorer and multi-currency API tests
        run: node scripts/test_multicurrency.js

      - name: Upload log files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-btcdao-logs
          path: logs/

  deploy-multinode:
    needs: build-test-matrix
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docker Swarm (EU/US/Asia)
        run: |
          docker stack deploy -c deploy/dao-swarm.yaml dao
      - name: Post-deploy healthcheck
        run: docker service ls
      - name: Notify community
        run: node scripts/notify_community.js
