[default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
cache = true
optimizer = true
optimizer_runs = 200
evm_version = "london"
solc_version = "0.8.19"

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${WEB3_INFURA_PROJECT_ID}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"

[profile.default]
ffi = true
auto_detect_remappings = true
